server:
  port: 20443


spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: student-realm
  resource: student-app
  public-client: true
  security-constraints[0].authRoles[0]: student
  security-constraints[0].securityCollections[0].patterns[0]: /v1/student/*
  principal-attribute: preferred_username
